# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CID Gamified Training' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CID Gamified Training
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Surge', '~> 2.3.0'

  target 'CID Gamified TrainingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CID Gamified TrainingUITests' do
    # Pods for testing
  end
end
